### ISSUE TITLE
IgbButton - the styling of "background-color" has not been applied.

### ISSUE THREAD

**Issue by jsakamotoIGJP** [IgniteUI/igniteui-xplat-docs#436]
1. Visit [the "Blazor Button Overview" page and scroll down to the "Styling" section](https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/button#styling).
2. You can see the example of the styling Blazor Button. However, **the background-color specification has not been applied**. (See also the screen shot below)

![image](https://user-images.githubusercontent.com/102948935/188554580-56f5a047-e219-4f3f-966d-2878157f374f.png)

----

P.S.

I could change the background color of the Blazor Button with the changing of styling definition like the following.

From:
```css
igc-button::part(base) {
    background-color: #e99221;
    color: #011627;
    padding: 18px;
}
```

To:
```css
igc-button::part(base) {
    color: #011627;
    padding: 18px;
}

/* 👇 I have to apply the background color to the "before" pseudo-element on the Blazor Button. */
igc-button::part(base)::before {
    background-color: #e99221;
}
```

However, `igc-button` (the Button component of "Ignite UI for WebComponents") works well with the example code.

(https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/button#styling)
![image](https://user-images.githubusercontent.com/102948935/188556189-171ceeed-48a1-437b-9b49-72898d9b383f.png)

**Is that an IgbButton-specific bug?** (not a document issue?) If it is yes, should I make a bug report to another GitHub repository?

Or, Is that **by design?** Is that **intensional incompatible Between Ignite UI for Blazor and WebComponents**?
